name:                tex
version:             0.1.0.0
github:              "alpacaaa/tex-file-explorer"
license:             BSD3
author:              "Marco Sampellegrini"
maintainer:          "babbonatale@alpacaaa.net"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/alpacaaa/tex-file-explorer#readme>

dependencies:
- base
- containers
- directory
- filepath
- pointedlist
- relude
- termbox
- unix

library:
  source-dirs: src

ghc-options:
  - -Wall
  - -Werror

default-extensions:
- LambdaCase
- NoImplicitPrelude
- OverloadedStrings
- StrictData

executables:
  tex-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tex

tests:
  tex-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - tex
